baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Hugo Learn Documentation"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= false

[params]
  editURL = "https://github.com/biograbber/biograbber-org/edit/master/content/"
  description = "Documentation for Hugo Learn Theme"
  author = "Mathieu Cornic"
  showVisitedLinks = false
  disableNextPrev = true
  disableShortcutsTitle = true
  disableToc = true


[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Documentation for Hugo Learn Theme"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Github"
identifier = "ds"
url = "https://github.com/biograbber/biograbber"
weight = 10